apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pinger-deployment
  labels:
    app: redis-pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pinger
  template:
    metadata:
      labels:
        app: redis-pinger
    spec:
      containers:
      - name: redis-pinger
        image: jpgouin/redis-pinger:arm64
        env:
          # These environment variables configure the Redis connection.
          # We assume a Redis service is running in the cluster with the name 'redis-service'.
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6397"
      # The default restart policy is "Always", which means Kubernetes will
      # automatically restart the container if it exits with an error (crashes).
      restartPolicy: Always
